services:
  rss-telegram:
    image:  asterix94/rss-telegram:latest
    container_name: rss-telegram
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=your_bot_token_here
      - TELEGRAM_CHAT_ID=your_chat_id_here
      - INCLUDE_DESCRIPTION=true
      - DISABLE_NOTIFICATION=true
      - CHECK_INTERVAL=3600
      - FEEDS_FILE=/app/data/feeds.txt
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"